### ISSUE TITLE
CVE

### ISSUE THREAD

**Issue by Shotokanman** [SabyasachiRana/WebMap#14]
It does not seem to be finding CVE's when I click on the link.

**Comment by variamus** [comment]
Same here :/

**Comment by stevecharon** [comment]
I am observing this as well. Initially I thougt this is my firewall, but after enabling access to the cve site mentioned in cve.py I get
---------start docker log snippet ------------
Traceback (most recent call last):
  File "/opt/nmapdashboard/nmapreport/nmap/cve.py", line 113, in <module>
    getcve(sys.argv[1])
  File "/opt/nmapdashboard/nmapreport/nmap/cve.py", line 81, in getcve
    if r.json() is not None:
  File "/usr/lib/python3/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
-----------end docker log snippet--------
so I think this is some bug or api of cve changed perhaps.

**Comment by tmanok** [comment]
Does anyone know if the maintainer is leaving this project? They have code commits to other projects but there doesn't appear to be much activity.
